apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: tests
spec:
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.0
        command: ["-text=\"hello weird\""]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5678
