apiVersion: v1
kind: Service
metadata:
  name: py-api-service
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-api-deployment
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: python-api
          image: christiancavuti/python-redis:0.1.0
          env:
            - name: REDIS_HOST
              value: redis-service    
